version: "3.8"

services:
  dock-banking:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_APP: banking
      FLASK_ENV: development
